#5-1
num = 20
value = (3*4)
print(f"\n{value} which is not equal to {num}")
print(num==value)
value = (3*5)
print(f"\n{value} which is not equal to {num}")
print(num==value)
value = (4*5)
print(f"\n{value} which is equal to {num}")
print(num==value)
value = (5*6)
print(f"\n{value} which is not equal to {num}")
print(num==value)
value = (12+8)
print(f"\n{value} which is equal to {num}")
print(num==value)
value = (40/2)
print(f"\n{value} which is equal to {num}")
print(num==value)
value = (3*4+6)
print(f"\n{value} which is not equal to {num}")
print(num==value)
value = (3*4+8)
print(f"\n{value} which is equal to {num}")
print(num==value)
value = (3*4)
print(f"\n{value} which is not equal to {num}")
print(num==value)
value = (2**3+2*6)
print(f"\n{value} which is equal to {num}")
print(num==value)

#5-2
favourite_team = 'man utd'
if favourite_team != 'Liverpool':
	print("\nGlory glory Man Utd!")
num=10
print(num==10)
value = (2*5)
print(f"\n{value} which is equal to {num}")
print(num==value)
value = (5*6)
print(f"\n{value} which is not equal to {num}")
print(num==value)

